### ISSUE TITLE
Syntax Error in JSON

### ISSUE THREAD

**Issue by simonmaass** [elgentos/LargeConfigProducts#11]
Hello,

I installed your module and on some products it works and on some i get the following error:

![unbenannt](https://user-images.githubusercontent.com/32599710/43825802-f646af5c-9af5-11e8-86e1-07b5fc5d6836.png)

Any ideas where to start looking? Thank you!

**Comment by peterjaap** [comment]
What's the content of the JSON? Also read https://github.com/elgentos/LargeConfigProducts/issues/8

**Comment by simonmaass** [comment]
yeah i read that issue...

seems to be here:

    {
        "[data-role=swatch-options]": {
            "Magento_Swatches/js/swatch-renderer": {
                "jsonConfig": null<? /* @escapeNotVerified */ //echo $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": {"173":{"68":{"type":"0","value":"CCL1","label":"CCL1"},"69":{"type":"0","value":"CCL2","label":"CCL2"},"208":{"type":"0","value":"CCL3","label":"CCL3"}},"93":{"87":{"type":"1","value":"#9c7e5b","label":"Mode"},"92":{"type":"1","value":"#1a212e","label":"Mondscheinblau"},"96":{"type":"1","value":"#ffffff","label":"Wei\u00df"},"97":{"type":"1","value":"#998a61","label":"Bronze"},"99":{"type":"1","value":"#d2a17b","label":"Ros\u00e9"},"200":{"type":"1","value":"#000000","label":"Schwarz"},"265":{"type":"1","value":"#f0b497","label":"Caramel"}}},
                "mediaCallback": "https://shop.meevo.de/swatches/ajax/media/",
                "gallerySwitchStrategy": "replace"
            },
            "Magento_Swatches/js/configurable-customer-data": {
                    "swatchOptions": null            }
        }
    }

Here:
` "jsonConfig": null<? /* @escapeNotVerified */ //echo $swatchOptions = $block->getJsonConfig() ?>,`

**Comment by DavidLambauer** [comment]
Hi, I tried to debug the whole thing a little. When I call the product options in the browser to see the JSON, I get a huge response (we have a lot of variants). The response itself is valid json. I couldn't find any syntax issues.


We are running M2 CE Version 2.2.5

**Comment by peterjaap** [comment]
Maybe remove `<? /* @escapeNotVerified */ //echo $swatchOptions = $block->getJsonConfig() ?>` after `"jsonConfig": null` ?

Its weird because that doesn't give me any issues on my installation but seeing as the JSON error states a `<`, that must be it.

**Comment by peterjaap** [comment]
Maybe your PHP installation has short tags disabled? That might explain it. Changing `<?` to `<?php` might in that case also solve the issue.

**Comment by DavidLambauer** [comment]
Yeeees! That's the issue!  Short Tags were configured for production... Wouldn't be a hard thing to change it in the module, right? Shall I add a PR for that xD

**Comment by peterjaap** [comment]
Sure :)
