### ISSUE TITLE
Frontend fetch does not take store view into account

### ISSUE THREAD

**Issue by lfglopes** [elgentos/LargeConfigProducts#20]
On the frontend side of things, the configurations seem to be loaded from the following endpoint:

`/lcp/fetch/productOptions?productId=:productId`

Turns out I have two different store views for each language, and the results for the default language always come out. If I change the endpoint to, say,

`/de/lcp/fetch/productOptions?productId=:productId`

Then the right results come out.

**Comment by peterjaap** [comment]
Aah right, good catch. In the project we've built this for we use separate domains so we hadn't run into this yet. Could you do a PR?

**Comment by lfglopes** [comment]
sure

**Comment by lfglopes** [comment]
I guess this is fixed now :)

I'll take the opportunity to thank you guys for publishing this piece, you saved me (and others I can assume) from a good headache. ;)

**Comment by peterjaap** [comment]
@lfglopes and thank you for your contribution :raised_hands:
