### ISSUE TITLE
Elgentos_LargeConfigProducts/js/configurable-customer-data-mixin

### ISSUE THREAD

**Issue by gaiterjones** [elgentos/LargeConfigProducts#44]
Could you please briefly explain the purpose of the js code Elgentos_LargeConfigProducts/js/configurable-customer-data-mixin

It's causing an error in 2.3.3.

**Comment by peterjaap** [comment]
It selects the first option available in a swatch.

**Comment by gaiterjones** [comment]
OK - I had kinda figured that out but wanted to check.
