### ISSUE TITLE
Compatibility with Magento 2.4.2

### ISSUE THREAD

**Issue by alelnro1** [elgentos/LargeConfigProducts#49]
Is the extension planned to be compatible with the latest magento version?

**Comment by gaiterjones** [comment]
@alelnro1 I am using this module in production on Magento 2.4.2-p1 stores.

I recommend installing it manually, as we have not yet updated the composer dependencies for the latest Magento framework versions.

**Comment by jorgb90** [comment]
Why not update it then? Makes it much easier ;-)
